In [99]:
import pandas as pd

In [100]:
df = pd.read_csv("dados/confrontos/historico_confrontos_ciclo26.csv")

display(df.head())

   Unnamed: 0        date home_team     away_team  home_score  away_score
0       45802  2022-12-30      Iraq        Kuwait         1.0         0.0
1       45811  2023-01-06      Iraq          Oman         0.0         0.0
2       45818  2023-01-09    Sweden       Finland         2.0         0.0
3       45820  2023-01-09      Iraq  Saudi Arabia         2.0         0.0
4       45823  2023-01-10     Qatar       Bahrain         1.0         2.0

In [101]:
qualified_teams = [
    "Canada",
    "United States",
    "Mexico",
    "Curacao",
    "Haiti",
    "Panama",
    "Japan",
    "Iran",
    "Uzbekistan",
    "South Korea",
    "Jordan",
    "Australia",
    "Qatar",
    "Saudi Arabia",
    "New Zealand",
    "Argentina",
    "Brazil",
    "Ecuador",
    "Uruguay",
    "Colombia",
    "Paraguay",
    "Morocco",
    "Tunisia",
    "Egypt",
    "Algeria",
    "Ghana",
    "Cape Verde",
    "South Africa",
    "Ivory Coast",
    "Senegal",
    "England",
    "France",
    "Croatia",
    "Portugal",
    "Norway",
    "Netherlands",
    "Germany",
    "Switzerland",
    "Austria",
    "Belgium",
    "Spain",
    "Scotland",
    "Turkey",
    "Czech Republic",
    "Sweden",
    "Bosnia and Herzegovina",
    "DR Congo",
    "Iraq"
]

In [102]:
df_stats = pd.DataFrame({"team": qualified_teams})
df_stats = df_stats.set_index("team")
df_stats["wins"] = 0
df_stats["draws"] = 0
df_stats["loses"] = 0
df_stats["points"] = 0
df_stats["games_played"] = 0

display(df_stats.head())

               wins  draws  loses  points  games_played
team
Canada            0      0      0       0             0
United States     0      0      0       0             0
Mexico            0      0      0       0             0
Curacao           0      0      0       0             0
Haiti             0      0      0       0             0

In [103]:
for row in df.itertuples():
    home, away = row.home_team, row.away_team
    home_score, away_score = row.home_score, row.away_score

    if home in qualified_teams: df_stats.at[home, "games_played"] += 1
    if away in qualified_teams: df_stats.at[away, "games_played"] += 1
    
    if home_score > away_score:
        if home in qualified_teams: df_stats.at[home, "wins"] += 1
        if away in qualified_teams: df_stats.at[away, "loses"] += 1
        
    elif away_score > home_score:
        if home in qualified_teams: df_stats.at[home, "loses"] += 1
        if away in qualified_teams: df_stats.at[away, "wins"] += 1
        
    else:
        if home in qualified_teams: df_stats.at[home, "draws"] += 1
        if away in qualified_teams: df_stats.at[away, "draws"] += 1

df_stats["points"] = df_stats["wins"]*3 + df_stats["draws"]
df_stats["points_per_game"] = round(df_stats["points"] / df_stats["games_played"],2)
df_stats = df_stats.sort_values(by="points", ascending=False)
display(df_stats.head())

               wins  draws  loses  points  games_played  points_per_game
team
Morocco          35      9      2     114            46             2.48
Mexico           25     15      9      90            49             1.84
United States    25      9     17      84            51             1.65
Colombia         23      9      6      78            38             2.05
Argentina        25      2      4      77            31             2.48